### ISSUE TITLE
README installation instructions do not work

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/krill-sync#3]
The README instructions cause compilation errors with `cargo install`. They should be updated to:

1. Refer to the latest release tag v0.1.2, not v0.1.0.
2. Instruct to use `--locked`.

This command works with Rust 1.51.0 on Ubuntu 18.04:

```
$ cargo install --git https://github.com/NLnetLabs/krill-sync.git --tag v0.1.2 --locked
...
   Installed package `krill-sync v0.1.1 (https://github.com/NLnetLabs/krill-sync.git?tag=v0.1.2#aa809c2f)` (executable `krill-sync`)
```
